# .circleci/config.yml

# Other required configuration

jobs:
  # Other jobs

  # 👇 Adds Chromatic as a job
  chromatic-deployment: 
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
        # 👇 Runs the Chromatic CLI
      - run: yarn chromatic --project-token=${CHROMATIC_PROJECT_TOKEN}


workflows:
  # 👇 Adds Chromatic to the workflow
  chromatic-deploy:
    jobs:
      - chromatic-deployment # 👈 Runs the Chromatic job implemented above